name: Trigger deploy to QA

on:
  workflow_dispatch:

permissions:
  pull-requests: write

jobs:
  pr:
    runs-on: ubuntu-22.04
    steps:
      - name: checkout
        uses: actions/checkout@v3
        with:
          ref: main

      - name: pull-request
        uses: repo-sync/pull-request@v2
        with:
          destination_branch: "qa"
          pr_title: "Pulling ${{ github.ref }} into qa"
          pr_label: "auto-pr" 
          pr_draft: true
          github_token: ${{ github.token }}
  qa:
    needs: ["pr"]
    runs-on: ubuntu-22.04
    environment: qa
    steps:
      - name: checkout
        uses: actions/checkout@v3
        with:
          fetch-depth: 0
          ref: qa

      - name: close PR
        run: gh pr close --comment "Closing PR, branch updated via pipeline"
        env:
          GITHUB_TOKEN: ${{ github.token }}

      - name: Fast forward QA
        run: |
          git config user.name github-actions
          git config user.email github-actions@github.com
          git merge origin/main --ff-only
          git push