name: Trigger deploy to QA

on:
  push:
    branches:
      - main

permissions:
  pull-requests: write

jobs:
  pr:
    runs-on: ubuntu-22.04
    outputs:
      pr_id: ${{ steps.open-pr.outputs.pr_number }}
    steps:
      - name: checkout
        uses: actions/checkout@v3

      - name: pull-request
        id: open-pr
        uses: repo-sync/pull-request@v2
        with:
          destination_branch: "qa"
          pr_title: "Pulling ${{ github.ref }} into qa"
          pr_label: "auto-pr" 
          pr_draft: true
          github_token: ${{ github.token }}
  qa:
    needs: ["pr"]
    runs-on: ubuntu-22.04
    environment: qa
    permissions:
      contents: write      
    steps:
      - name: checkout QA branch
        uses: actions/checkout@v3
        with:
          fetch-depth: 0
          ref: qa

      - name: close PR
        run: gh pr close ${{ needs.pr.outputs.pr_id }} --comment "Closing PR, branch updated via pipeline"
        env:
          GITHUB_TOKEN: ${{ github.token }}

      - name: Fast forward QA
        run: |
          git config user.name github-actions
          git config user.email github-actions@github.com
          git merge origin/main --ff-only
          git push